name: ci
on:
  pull_request:
    paths-ignore:
    - '.github/workflows/release.yaml'
    - '*.md'
    - 'dist/*'
    - 'tools/package'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres:
        - version: "14"
        - version: "13"
        - version: "12"
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: Install postgres
        run: |
          sudo apt-get update
          sudo apt-get install -y lsb-release wget gnupg2
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get -y install postgresql-${{matrix.postgres.version}} postgresql-server-dev-${{matrix.postgres.version}}

      - uses: Swatinem/rust-cache@v1

      - name: Install cargo-pgx
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-pgx --git https://github.com/timescale/pgx --branch promscale-staging

      - name: Cache pgx
        id: cache-pgx
        uses: actions/cache@v2
        with:
          path: ~/.pgx
          key: dot-pgx-${{ matrix.postgres.version }}-cargo-${{ hashFiles('**/Cargo.*') }}

      - name: Initialize pgx
        if: ${{ steps.cache-pgx.outputs.cache-hit != 'true' }}
        uses: actions-rs/cargo@v1
        with:
          command: pgx
          args: init --pg${{ matrix.postgres.version }} /usr/lib/postgresql/${{ matrix.postgres.version }}/bin/pg_config
      
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: pgx
          args: test pg${{ matrix.postgres.version }}

